
# Spotify Demand Forecast - dbt Project Configuration
name: 'spotify_demand_forecast'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'spotify_demand_forecast'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Variables for feature engineering
vars:
  # Lag periods for time series features
  lag_periods: [1, 7, 14, 30]
  # Rolling window sizes
  rolling_windows: [7, 14, 30]
  # Minimum date for feature calculation (warmup period)
  warmup_days: 30

# Model configurations by layer
models:
  spotify_demand_forecast:
    # Staging layer: lightweight views for data cleaning
    staging:
      +materialized: view
      +schema: staging

    # Intermediate layer: feature engineering tables
    intermediate:
      +materialized: table
      +schema: intermediate
      # Redshift-specific optimizations
      +dist: auto
      +sort: ['date', 'track_id']

    # Mart layer: final ML-ready features
    mart:
      +materialized: incremental
      +schema: mart
      +unique_key: stream_key
      +incremental_strategy: delete+insert
      +dist: auto
      +sort: ['date', 'track_id', 'region']
